### ISSUE TITLE
Using PNPM

### ISSUE THREAD

**Issue by oleteacher** [zinedkaloc/aipage.dev#11]
Hello. Nice project you have going.

Like to experiment with this in a classroom environment. We have local dev servers that run AlmaLinux 8.

When getting to install step:  `pnpm install` get the following error:

```
[root@room121server ~]# pnpm install
-bash: pnpm: command not found
```

Having heck of time trying to make PNPM install/make work on AlmaLinux 8. Is there any another way to install aipage.dev not using PNPM?

**Comment by zinedkaloc** [comment]
Could you please try with below commands? 🙏

`npm install`

or 

`yarn install`

**Comment by oleteacher** [comment]
Thanks for reply!

I used npm install and get the following:

```
[root@room121server aipage.dev]# npm install
npm WARN config init.module Use `--init-module` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: next-openai@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0-0" from react-html-parser@2.0.2
npm ERR! node_modules/react-html-parser
npm ERR!   react-html-parser@"^2.0.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /www/server/nodejs/v12.13.1/cache/_logs/2023-07-29T15_59_44_721Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /www/server/nodejs/v12.13.1/cache/_logs/2023-07-29T15_59_44_721Z-debug-0.log
```

Pretty strange. No Node guru by any means but have never had issue in past with straight forward installs like yours. 

This may be something IT department has locked down and will have to query them Monday during work hours.

**Comment by oleteacher** [comment]
Must be some type of restriction on our school network / server. Never got it working, will close this now and maybe try later.
