### ISSUE TITLE
GPT answer text inside page box

### ISSUE THREAD

**Issue by sukerberk1** [zinedkaloc/aipage.dev#12]
Creating a page for the second time when the box is already filled with previously generated landing page causes an answer text apperance on the box's top.
![bug](https://github.com/zinedkaloc/aipage.dev/assets/113460945/58949c87-0ea7-44e5-883f-7ed6cd64c29b)

**Comment by sukerberk1** [comment]
As i see, this appears only in downloaded git repo as on aipage.dev it is already fixed?

**Comment by sukerberk1** [comment]
![bug2](https://github.com/zinedkaloc/aipage.dev/assets/113460945/07fc7a4a-2cd8-4cae-9d11-f56b499ec4fa)
Additionally, after typing "landing page for drug dealer business" this appears. 😄

**Comment by Matrx123** [comment]
assign #12
