### ISSUE TITLE
Altogic didn't let new user create new account anymore

### ISSUE THREAD

**Issue by amazingnerd** [zinedkaloc/aipage.dev#31]
# Feature Request

**Description**
Altogic didn't let new user create new account anymore.

**Proposed Solution**
Can we move from using Altogic to use Appwrite? It's also backend as a service platform too.

<img width="464" alt="image" src="https://github.com/zinedkaloc/aipage.dev/assets/87475722/22e6e93c-92a7-4ec4-b162-94e3c6b075d7">

**Comment by gradam** [comment]
Seems like Altogic has been discontinued. :( 
 Im afraid, atm. this renders this project unusable

**Comment by zinedkaloc** [comment]
Thanks for your interest! We're working on a new version set to release in 2 weeks. Stay tuned!

**Comment by javaskript** [comment]
> Thanks for your interest! We're working on a new version set to release in 2 weeks. Stay tuned!

Will the new version not rely on Altogic? Is it possible for us to entirely self-host it without third-party dependency?

**Comment by xarcnovn** [comment]
hello @zinedkaloc, I'd love to use your repo in one of my projects, but without Altogic replacement it may be troublesome. Could you tell us how when you're planning to release a new version? Thanks!

**Comment by amazingnerd** [comment]
Hi, will this repo be updated with new version. It has no update for over 6 months. The https://aipage.dev/ got updated but this repo is still outdated.
<img width="908" alt="image" src="https://github.com/zinedkaloc/aipage.dev/assets/87475722/e2bd475c-274f-4f21-877a-0ce1273401d8">

**Comment by zinedkaloc** [comment]
Hi everyone;

I wanted to provide an update regarding the development of the v2 of our project.

Unfortunately, we have made the decision to discontinue the open-source development of the v2. There are several reasons behind this decision, including:

1. Complexity
2. Resource Allocation
3. Customer Success
4. Regulatory Compliance
5. Focus on Support

We appreciate your understanding.
